name: Build 8188eu.ko
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu make bc clang lld llvm libssl-dev python-is-python3

      - name: Clone driver
        run: git clone https://github.com/aircrack-ng/rtl8188eus

      - name: Clone kernel
        run: git clone https://github.com/liyafe1997/kernel_xiaomi_sm8250_mod -b android15-lineage22-mod --depth=1 kernel
      - name: Prepare kernel
        run: cd kernel && make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- cas_defconfig && make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- modules_prepare -j$(nproc)

      - name: Fix and build module
        run: |
          cd rtl8188eus
          sed -i 's/gfp_t kflags = in_atomic/u16 kflags = in_atomic/g' os_dep/linux/rtw_cfgvendor.c
          sed -i 's/-Werror/-Wno-error/g' Makefile
          make ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- KSRC=../kernel/out
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 8188eu-ko
          path: rtl8188eus/8188eu.ko
